version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0


jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - azure-cli/login-with-user:
          alternate-tenant: true 
          azure-password: "$AZURE_PASSWORD" 
          azure-tenant: "$AZURE_TENANT"
          azure-username: "$AZURE_USERNAME" 

workflows:
  example-workflow:
    jobs:
      - example-job
