version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0


jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    parameters:
      alternate-tenant:
        default: false
        description: Use an alternate tenant
        type: boolean
    steps:
      - run:
          command: |
            az login \
              <<parameters.alternate-tenant>> \
              --tenant $AZURE_TENANT \
              -u $AZURE_USERNAME \
              -p $AZURE_PASSWORD
          name: Login to the Azure CLI via username/password

workflows:
  example-workflow:
    jobs:
      - example-job
