version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0


jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - azure-cli/login-with-user:
          alternate-tenant: true 
          azure-password: "Aditadit1234!!"
          azure-tenant: "6f4432dc-20d2-441d-b1db-ac3380ba633d"
          azure-username: "pattarapol.plasma@mail.kmutt.ac.th" 

workflows:
  example-workflow:
    jobs:
      - example-job
