version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0


jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - run:
          command: az login \
          <<#parameters.alternate-tenant>> \
          --tenant $<<parameters.azure-tenant>> <</parameters.alternate-tenant>> \
          -u $<<parameters.azure-username>> \
          -p $<<parameters.azure-password>>
        name: Login to the Azure CLI via username/password 

workflows:
  example-workflow:
    jobs:
      - example-job
